In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pull_data

In [3]:
import pandas as pd
from datetime import date

# Pull down data
all_cpi_df = pull_data.pull_cpi_data(start_date = date(2020, 1, 1), end_date = date(2022, 1, 1), item = 'All items')

# normalize date column to pandas datetime to avoid Timestamp vs date comparison issues
all_cpi_df['date'] = pd.to_datetime(all_cpi_df['date'])

all_cpi_df

INFO:pull_data:get_cpi_range called with item=All items
INFO:pull_data: Function: _fetch_item_data
INFO:pull_data: Function: diff_month
INFO:pull_data: Function: _calculations

         date  cpi_value
0  2020-01-01    257.971
0  2020-02-01    258.678
0  2020-03-01    258.115
0  2020-04-01    256.389
0  2020-05-01    256.394
0  2020-06-01    257.797
0  2020-07-01    259.101
0  2020-08-01    259.918
0  2020-09-01    260.280
0  2020-10-01    260.388
0  2020-11-01    260.229
0  2020-12-01    260.474
0  2021-01-01    261.582
0  2021-02-01    263.014
0  2021-03-01    264.877
0  2021-04-01    267.054
0  2021-05-01    269.195
0  2021-06-01    271.696
0  2021-07-01    273.003
0  2021-08-01    273.567
0  2021-09-01    274.310
0  2021-10-01    276.589
0  2021-11-01    277.948
0  2021-12-01    278.802
0  2022-01-01    281.148

        date  cpi_value  cpi_annualized  cpi_relative_value
0 2020-01-01    257.971             NaN            1.000000
0 2020-02-01    258.678        3.338770            1.002741
0 2020-03-01    258.115       -2.580703            1.000558
0 2020-04-01    256.389       -7.735690            0.993868
0 2020-05-01    256.394        0.023404            0.993887
0 2020-06-01    257.797        6.767732            0.999326
0 2020-07-01    259.101        6.241639            1.004380
0 2020-08-01    259.918        3.850169            1.007547
0 2020-09-01    260.280        1.684158            1.008951
0 2020-10-01    260.388        0.499063            1.009369
0 2020-11-01    260.229       -0.730297            1.008753
0 2020-12-01    260.474        1.135643            1.009703
0 2021-01-01    261.582        5.225675            1.013998
0 2021-02-01    263.014        6.770708            1.019549
0 2021-03-01    264.877        8.839013            1.026770
0 2021-04-01    267.054       10.320967            1.035209
0 2021-05-01    269.195       10.056278            1.043509
0 2021-06-01    271.696       11.736501            1.053204
0 2021-07-01    273.003        5.927836            1.058270
0 2021-08-01    273.567        2.507457            1.060456
0 2021-09-01    274.310        3.308293            1.063337
0 2021-10-01    276.589       10.438161            1.072171
0 2021-11-01    277.948        6.058087            1.077439
0 2021-12-01    278.802        3.749970            1.080749
0 2022-01-01    281.148       10.578161            1.089843

In [3]:
all_cpi_df

,date,cpi_value,date,cpi_value,date,cpi_value,date,cpi_value,date,cpi_value,...,date,cpi_value,date,cpi_value,date,cpi_value,date,cpi_value,date,cpi_value
0,NaN,NaN,2020-01-01,257.971,2020-02-01,258.678,2020-03-01,258.115,2020-04-01,256.389,...,2021-09-01,274.31,2021-10-01,276.589,2021-11-01,277.948,2021-12-01,278.802,2022-01-01,281.148